# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-08 06:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date(2017, 3, 8)),
        ),
    ]
